FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas

#FROM apache/airflow:latest

#USER root
#RUN apt-get update && \
#
#    apt-get -y install git && \
#
#    apt-get clean
#USER airflow